### ISSUE TITLE
Line through the UI, unknown cause

### ISSUE THREAD

**Issue by rinaraindrop** [Arrenton/KingdomHeartsPlugin#29]
Upon toggling every option I could seem to change in the configuration, I wasn't able to find something to make this line through the hp bar disappear, I'm not sure what seems to be causing it but it makes it look very unclean, restarting the plugin didn't seem to do anything either.
![ffxiv_dx11_2021-12-24_13-42-13](https://user-images.githubusercontent.com/29421556/147353592-30c30284-24d2-4570-b7d5-b6e402e883af.png)

**Comment by Arrenton** [comment]
This happens when scale is higher than 1. I have no idea why it happens either, and trust me that I tried to fix it.

**Comment by MrSunabouzu** [comment]
Oh this is an old gamedev problem. It's mildly expensive to fix, you have to use an alpha mask of some sort on the texture instead of letting the png solve for transparency. That or change the way the png is rendered but I don't know if you have control over that.

Ok so example from Half Life 2, this texture in the game is red text on a black background, and they used the alpha channel to cut out the letters. https://developer.valvesoftware.com/w/images/7/75/Alpha_sign.png

Notice how you can see the black before it cuts off into the sky? that's because the texture has been scaled up and now has new subpixels, so whatever garbage information that was there before but was hidden becomes much clearer. In this case if the texture was text on a transparent background, instead of the bits of black you'd get a fade like what's happening in the mod.

The problem is a fix could easily require a re-write, make the mod more expensive for users with low end machines, or any number of headaches. I personally don't mind how it is now even at 4k because I just commissioned an artist to draw my catboy in the kh2 style so it covers up the seams pretty well. I'll attach a zip with a tga file of how I *think* altering the texture for the ring health segment could get rid of this bug but again, it's probably not worth it in this case.

[alpha_example.zip](https://github.com/Arrenton/KingdomHeartsPlugin/files/8497205/alpha_example.zip)
