### ISSUE TITLE
cant seem to get the low hp noise to work

### ISSUE THREAD

**Issue by RubiiHoshii** [Arrenton/KingdomHeartsPlugin#33]
i am attempting to get a low hp sound working (using a sound file from another user on the issues section) and i cant seem to get it to work even tho im putting the file location? i just dunno whats going on lol i made my account to try and ask about this

**Comment by Arrenton** [comment]
Can you show me the path you're using? You can exclude any personal info if there's any the path.

**Comment by RubiiHoshii** [comment]
i last tried C:\Users\(my real name is here)\Desktop\ffxiv stuff\crithp sound.  with the file for the sound being the only thing in the crithp sound folder

**Comment by RubiiHoshii** [comment]
i missed a \ typing it again but ya know

**Comment by Arrenton** [comment]
Crithp sound is the name of the folder?

**Comment by RubiiHoshii** [comment]
yea that is the folder name, the sound being called "CriticalHP"

**Comment by Arrenton** [comment]
Then the path is incomplete. You'd need to make it "C:\Users(my real name is here)\Desktop\ffxiv stuff\crithp sound\CriticalHP.wav"

**Comment by RubiiHoshii** [comment]
oooohhhh ok cool thank you! when its updated ill try it lol

**Comment by RubiiHoshii** [comment]
it worked, thank you!

**Comment by xkurosawax** [comment]
I am having an issue to get both my portrait and sound working. I placed the directory in the correct pathway and I am not seeing any results. The pathway I have is C:\Users\danie\Pictures\Ffxiv\image.png and nothing is happening when I hit the set button and save. Is there something I am missing? Please let me know because this is a cool mod! :D
